name: Mondoo Custom AWS Scan (Bash Inline)

on:
  workflow_dispatch:
    inputs:
      awsRegion:
        description: 'AWS Region to scan'
        required: true
        default: 'us-east-1' 

permissions:
  contents: read

jobs:
  mondoo_aws_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Install cnspec CLI
      - name: Install Mondoo cnspec
        run: |
          # Download and install the cnspec binary directly
          curl -sS https://install.mondoo.com/sh | sh
          # Ensure cnspec is in the path
          echo "$HOME/.mondoo/bin" >> $GITHUB_PATH

      # 2. Configure AWS Credentials
      # This step authenticates the runner to AWS using repository secrets.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.awsRegion }}
          
      # 3. Run Mondoo Scan with Custom Policy via Inline Bash
      - name: Run Mondoo Scan with Custom Policy
        # Use a simple 'run' block to execute the cnspec command directly.
        # Since cnspec is installed locally, the policy path is relative to the repo root.
        run: |
          cnspec scan aws \
            --policy-bundle ./mondoo-custom-policies/custom-s3-sg.mql.yaml \
            --output full \
            --incognito
        # Note: The policy file path is now relative to the repository root (e.g., ./mondoo-custom-policies/...)