name: Terraform Infra Pipeline

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
    inputs:
      securityScan:
        description: "Select IaC Security Scanner"
        required: true
        default: "checkov"
        type: choice
        options: ["checkov", "mondoo", "none"]

      enableDestroy:
        description: "Enable destroy stage?"
        required: true
        default: "false"
        type: choice
        options: ["true", "false"]

jobs:
  # ====================================================================
  # STAGE 1: IaC Security Scan (Checkov OR Mondoo)
  # ====================================================================

  # 1A: Checkov Scan
  checkov:
    if: ${{ github.event.inputs.securityScan == 'checkov' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        run: pip install checkov

      - name: Create Reports Directory
        run: mkdir -p reports

      - name: Run Checkov on all modules
        id: checkov_scan
        run: |
          checkov -d terraform-project/ \
            --output junitxml \
            --output-file reports/checkov-report.xml || true

          if [ ! -s reports/checkov-report.xml ]; then
            echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?><testsuites></testsuites>" > reports/checkov-report.xml
          fi

      - name: Upload Checkov Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: reports/checkov-report.xml

      # - name: Publish Test Report
      #   if: always()
      #   uses: mikepenz/action-junit-report@v4
      #   with:
      #     report_paths: 'reports/checkov-report.xml'
      #     include_passed: true
          
  # 1B: Mondoo Scan
  mondoo_scan:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v4 # Use the latest version

          - name: Scan Terraform with Mondoo
            # 1. FIX: The correct action name is 'terraform-hcl' not 'terraform'.
            # 2. FIX: Use a stable version tag (e.g., v1) instead of 'main'.
            uses: mondoohq/actions/terraform-hcl@v1 
            with:
              # 3. FIX: 'with' is the correct block for action inputs, including secrets.
              # The input name is 'service-account-credentials', not MONDOO_CONFIG_BASE64.
              service-account-credentials: ${{ secrets.MONDOO_SERVICE_ACCOUNT }}
              
              # 4. FIX: Use a directory path instead of globbing (*.tf) for better reliability.
              # Assuming your files are in the repository root ('.').
              path: .
              
              # 5. RECOMMENDED: Add output paths to save the report
              report-junit: mondoo-report.xml
              
          - name: Publish Test Report
            if: always()
            uses: mikepenz/action-junit-report@v4
            with:
              report_paths: 'mondoo-report.xml'

  # ====================================================================
  # STAGE 2: Terraform Plan & Apply (Approval Handled by 'dev' Environment)
  # ====================================================================
  
  terraform:
    needs: [checkov, mondoo_scan]
    if: always() 
    runs-on: ubuntu-latest
    # 👇 This links the job to your protected environment
    environment: 
      name: dev
      # Optional: provides a link to the workflow run in the environment approval box
      # url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
    
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform -chdir=terraform-project init -backend-config=backend.tfvars
        
      - name: Terraform Plan
        # The runner executes Init and Plan successfully
        run: |
          terraform -chdir=terraform-project plan -out=tfplan
          terraform -chdir=terraform-project show -no-color tfplan > terraform-project/plan-summary.txt
          
      - name: Upload Terraform Plan Summary
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-summary
          path: terraform-project/plan-summary.txt

      # The job pauses HERE, waiting for 'santuCG' to approve the 'dev' environment.
      
      - name: Terraform Apply
        # This step runs ONLY after environment approval
        run: terraform -chdir=terraform-project apply -auto-approve tfplan

  # ====================================================================
  # STAGE 3: Destroy (Manual Approval Gate BEFORE Destroy)
  # ====================================================================
  
  destroy:
    if: ${{ github.event.inputs.enableDestroy == 'true' }}
    runs-on: ubuntu-latest
    needs: [terraform]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform -chdir=terraform-project init -backend-config=backend.tfvars

      # 👇 Manual Approval Action for Destroy
      - name: Manual Approval before Destroy
        uses: trstringer/manual-approval@v1
        with:
          approvers: santuCG # Set specific approver for the destroy action
          minimum-approvals: 1
          issue-title: "🚨 Approve Terraform Destroy"
          issue-body: "Approve to proceed with **DESTROYING** all resources in the **dev** environment."
          secret: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Terraform Destroy
        run: terraform -chdir=terraform-project destroy -auto-approve