name: Terraform Infra Pipeline

permissions:
  contents: read
  checks: write

on:
  workflow_dispatch:
    inputs:
      checkovScan:
        description: "Run Checkov Scan before plan/apply?"
        required: true
        default: "true"
        type: choice
        options: ["true", "false"]

      enableDestroy:
        description: "Enable destroy stage?"
        required: true
        default: "false"
        type: choice
        options: ["true", "false"]

      enableMondoo:
        description: "Run Mondoo Scan"
        required: true
        default: "false"
        type: choice
        options: ["true", "false"]

jobs:
  # Stage 1: Checkov Scan (Runs on Host Runner - No Docker Container)
  checkov:
    if: ${{ github.event.inputs.checkovScan == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Checkov
        # Using 'pip' is standard after 'setup-python' has configured the PATH
        run: pip install checkov
        
      - name: Create Reports Directory
        run: mkdir -p reports
        
      - name: Run Checkov on all modules
        # This now runs directly on the ubuntu runner and finds the path correctly
        run: checkov -d terraform-project/ --output junitxml --output-file reports/checkov-report.xml
        
      - name: Upload Checkov Report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: reports/checkov-report.xml
          
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: 'reports/checkov-report.xml'

# -----------------------------------------------------------------------------

  # Stage 2: Terraform Plan & Apply
  terraform:
    needs: [checkov]
    runs-on: ubuntu-latest
    environment: dev
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform -chdir=terraform-project init -backend-config=backend.tfvars
        
      - name: Terraform Plan
        run: |
          terraform -chdir=terraform-project plan -out=tfplan
          terraform -chdir=terraform-project show -no-color tfplan > terraform-project/plan-summary.txt
          
      - name: Upload Terraform Plan Summary
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-summary
          path: terraform-project/plan-summary.txt
          
      - name: Terraform Apply
        run: terraform -chdir=terraform-project apply -auto-approve tfplan

# -----------------------------------------------------------------------------

  # Stage 3: Destroy
  destroy:
    if: ${{ github.event.inputs.enableDestroy == 'true' }}
    runs-on: ubuntu-latest
    needs: [terraform]
    steps:
      - uses: actions/checkout@v4
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Terraform Init
        run: terraform -chdir=terraform-project init -backend-config=backend.tfvars
        
      - name: Terraform Destroy
        run: terraform -chdir=terraform-project destroy -auto-approve

# -----------------------------------------------------------------------------

  # Stage 4: Mondoo Scan
  mondoo:
    if: ${{ github.event.inputs.enableMondoo == 'true' }}
    runs-on: ubuntu-latest
    needs: [terraform]
    steps:
      - uses: actions/checkout@v4
        
      - name: Install Mondoo (cnspec)
        run: curl -sSL https://get.mondoo.com | bash
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          # 🚨 NOTE: 'ueu-north-1' is not a standard AWS region.
          # Replaced with a common region for demonstration. Use your correct region.
          aws-region: eu-north-1
          
      - name: Run Mondoo Scan
        run: cnspec scan aws --bundles policies/custom-s3-sg.mql.yaml --output json > mondoo-report.json
        
      - name: Upload Mondoo Report
        uses: actions/upload-artifact@v4
        with:
          name: mondoo-report
          path: mondoo-report.json