name: Mondoo AWS S3 Compliance Scan

on:
  workflow_dispatch:
    inputs:
      awsRegion:
        description: 'AWS Region to scan'
        required: true
        default: 'eu-north-1'

permissions:
  contents: read

jobs:
  mondoo-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Step 1: Install Mondoo via apt
      - name: Install Mondoo
        run: |
          sudo curl --retry 3 --retry-delay 10 -sSL https://releases.mondoo.com/debian/pubkey.gpg | sudo gpg --dearmor --output /usr/share/keyrings/mondoo-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/mondoo-archive-keyring.gpg] https://releases.mondoo.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/mondoo.list
          sudo apt update
          sudo apt install -y mondoo

      # # Step 2: Prepare Mondoo config securely
      # - name: Setup Mondoo config
      #   run: |
      #     mkdir -p ~/.config/mondoo
      #     echo "$MONDOO_CONFIG" > ~/.config/mondoo/config.yml
      #   env:
      #     MONDOO_CONFIG: ${{ secrets.MONDOO_CONFIG }}

      # Step 3: Run Mondoo Scan with Custom S3 Policy
      - name: Run Mondoo Scan
        run: |
          cnspec scan aws \
            --region "${{ github.event.inputs.awsRegion }}" \
            --policy-bundle mondoo-custom-policies/s3-policy.mql.yaml \
            --discover s3-buckets \
            --output full
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
