name: Mondoo Custom AWS Policy Scan

on:
  workflow_dispatch:
    inputs:
      awsRegion:
        description: 'AWS Region to scan'
        required: true
        default: 'us-east-1' 

permissions:
  contents: read

jobs:
  mondoo_aws_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Configure AWS Credentials (STANDARD, UNCHANGED)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.awsRegion }}

      # 2. Run Mondoo Scan with Custom Policy (NEW DOCKER METHOD)
      - name: Scan AWS Account with Custom Policy
        # Use the official Mondoo Docker image and pass the commands directly.
        # This bypasses any issues with the GitHub Action repository not being found.
        # This command runs cnspec, scanning the 'aws' target using the policy bundle.
        run: |
          docker run --rm \
            -v ${PWD}:/opt/repo \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_REGION \
            mondoo/cnspec:latest \
            scan aws \
            --policy-bundle /opt/repo/../../mondoo-custom-policies/custom-s3-sg.mql.yaml \
            --output full