name: Mondoo Custom AWS Policy Scan

on:
  workflow_dispatch:
    inputs:
      awsRegion:
        description: 'AWS Region to scan'
        required: true
        default: 'us-east-1' # Match your default region secret

permissions:
  contents: read

jobs:
  mondoo_aws_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Configure AWS Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.awsRegion }}

      # 2. Run Mondoo Scan with Custom Policy
      - name: Scan AWS Account with Custom Policy
        # Use the generic Mondoo cnspec action for scanning live cloud assets
        uses: mondoohq/mondoo-action@v1 
        with:
          
          # Target the AWS cloud provider
          target: aws
          
          # Specify the policy file to run (relative to the repo root)
          policy-bundle: ../../mondoo-custom-policies/custom-s3-sg.mql.yaml
          
          # Use 'full' output to see detailed results for every check
          output: full
          
          # The Mondoo action automatically runs: cnspec scan aws --policy-bundle .mondoo/policies/custom_aws.yml