name: Mondoo Custom AWS Scan (Live Environment)

on:
  # Allows you to trigger this workflow manually from the GitHub Actions tab
  workflow_dispatch:
    inputs:
      awsRegion:
        description: 'AWS Region to scan'
        required: true
        default: 'us-east-1' 

permissions:
  contents: read # Only needs read access to check out code and policies

jobs:
  mondoo_aws_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.awsRegion }}

      # 🎯 STEP A: DIAGNOSTIC CHECK
      - name: Verify Policy File Exists in Container
        run: |
          echo "Attempting to list the file at the specified path inside the container..."
          # This command must succeed before the scan can work.
          docker run --rm \
            -v $GITHUB_WORKSPACE:/opt/repo \
            mondoo/cnspec:latest \
            ls -l /opt/repo/mondoo-custom-policies/custom-s3-sg.mql.yaml

      # 🎯 STEP B: RUN SCAN
      - name: Run Mondoo Scan with Custom Policy
        run: |
          docker run --rm \
            -v $GITHUB_WORKSPACE:/opt/repo \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_REGION \
            mondoo/cnspec:latest \
            scan aws \
            --policy-bundle /opt/repo/mondoo-custom-policies/custom-s3-sg.mql.yaml \
            --output full \
            --incognito